### ISSUE TITLE
markdownView.load not working due to webkit networking problem

### ISSUE THREAD

**Issue by Stefanhym** [keitaoouchi/MarkdownView#14]
when I was trying the example code for how to use and run it on my phone, nothing appeared.
And I got this message from console:
**2017-09-14 01:42:41.275511+0800 tableview[2394:521302] Could not signal service com.apple.WebKit.WebContent: 113: Could not find specified service
2017-09-14 01:42:41.276706+0800 tableview[2394:521302] Could not signal service com.apple.WebKit.Networking: 113: Could not find specified service**
plz Any help?

**Comment by Stefanhym** [comment]
@keitaoouchi

**Comment by keitaoouchi** [comment]
Sorry, I don't have any solution.
