### ISSUE TITLE
![](//xxx) image tag not work

### ISSUE THREAD

**Issue by nswbmw** [keitaoouchi/MarkdownView#21]
```swift
import UIKit
import MarkdownView

class ViewControlle3: UIViewController {
  @IBOutlet weak var mdView: MarkdownView!
  
  override func viewDidLoad() {
    super.viewDidLoad()

    // not work
    mdView.load(markdown: "![](//dn-cnode.qbox.me/Fh2MIT1r4YStGl9ZEEzt7N4lEbqX)")
//    mdView.load(markdown: "![](//dn-cnode.qbox.me/Fh2MIT1r4YStGl9ZEEzt7N4lEbqX)", enableImage: true)
//    mdView.load(markdown: "![](http://dn-cnode.qbox.me/Fh2MIT1r4YStGl9ZEEzt7N4lEbqX)", enableImage: true)
  }
}
```

**Comment by keitaoouchi** [comment]
Thanks, I will investigate this later.
Maybe, protocol-relative URL is not recognized by markdown parser(markdown-it is used inside)?

#### `![](//dn-cnode.qbox.me/Fh2MIT1r4YStGl9ZEEzt7N4lEbqX)`
![](//dn-cnode.qbox.me/Fh2MIT1r4YStGl9ZEEzt7N4lEbqX)
Github's markdown preview does not recognize protocol-relative URL.

#### `![](https://dn-cnode.qbox.me/Fh2MIT1r4YStGl9ZEEzt7N4lEbqX)`
![](https://dn-cnode.qbox.me/Fh2MIT1r4YStGl9ZEEzt7N4lEbqX)
URL with protocol works well.

##### Note: 
- https://www.paulirish.com/2010/the-protocol-relative-url/
- https://github.com/markdown-it/mdurl
- https://jeremywagner.me/blog/stop-using-the-protocol-relative-url/
