### ISSUE TITLE
Can't load Image on MarkdownView

### ISSUE THREAD

**Issue by lucascorrea** [keitaoouchi/MarkdownView#32]
Hey Guys,

I have a problem with load image.
In the screenshot, we can see that the MarkdownView does not load the image, but the image exists on the folder.

Has anyone had the same problem as me? Could someone help me solve this bug, please?

![screenshot 2018-10-16 at 12 56 022](https://user-images.githubusercontent.com/385947/47015082-f8ae8100-d143-11e8-986a-2381c474103b.jpg)

**Comment by fujianjin6471** [comment]
I encountered exactly the same problem,  have you found a solution?

**Comment by lucascorrea** [comment]
> I encountered exactly the same problem, have you found a solution?

It's very stranger. In Simulator, it works but on the device not.

**Comment by brunnobraga** [comment]
A bit late to the party, but I think the issue is WKWebView doesn't have access to your AppData Documents folder by default.

For anyone coming here, it's worth connecting to WKWebView using Safari's web inspector and checking for any error messages on Network or Console.

**Comment by manuelzi** [comment]
Did anyone find a solution for displaying local images?

**Comment by lucascorrea** [comment]
Hey Manuelzi, I didn't remember how I fixed it, but you can see it on the file.

https://github.com/securityfirst/Umbrella_ios/blob/master/Umbrella/ViewControllers/Lesson/MarkdownViewController.swift

**Comment by manuelzi** [comment]
> Hey Manuelzi, I didn't remember how I fixed it, but you can see it on the file.
> 
> 
> 
> https://github.com/securityfirst/Umbrella_ios/blob/master/Umbrella/ViewControllers/Lesson/MarkdownViewController.swift

Thank you, will check it out!

**Comment by manuelzi** [comment]
@lucascorrea Got it working with MarkdownView. Just had to remove "file://" from the URL encoded string. Thanks again!

```
let imageElement: String = Bundle.main.path(forResource: "<FILENAME>", ofType: "png").map {
    let imageUrl = URL(fileURLWithPath: $0).absoluteString.replacingOccurrences(of: "file://", with: "")
    return "![](\(imageUrl))"
} ?? ""
```
