### ISSUE TITLE
Compiled error

### ISSUE THREAD

**Issue by turkeyaa** [keitaoouchi/MarkdownView#34]
Swift version 4.2.1

at the latest version 1.5.0

screenshot：
<img width="1151" alt="2018-11-06 2 39 53" src="https://user-images.githubusercontent.com/7940089/48047189-3ac26400-e1d2-11e8-8158-d066d0ce2d3b.png">

**Comment by keitaoouchi** [comment]
Maybe you are building MarkdownView with 4.1.x or lower version of Swift.
If you have something like below lines in your Podfile, please remove them.
```
post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['SWIFT_VERSION'] = '4.0'
    end
  end
end
```
